In [1]:
import numpy as np
import statsmodels.api as sm

In [2]:
x = [
...   [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
... ]

In [3]:
y = [4, 5, 20, 14, 32, 22, 38, 43]

In [4]:
x, y = np.array(x), np.array(y)

In [5]:
x = sm.add_constant(x)

In [6]:
x

array([[ 1.,  0.,  1.],
       [ 1.,  5.,  1.],
       [ 1., 15.,  2.],
       [ 1., 25.,  5.],
       [ 1., 35., 11.],
       [ 1., 45., 15.],
       [ 1., 55., 34.],
       [ 1., 60., 35.]])

In [7]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [8]:
model = sm.OLS(y, x)

In [9]:
results = model.fit()

In [10]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Wed, 08 Feb 2023   Prob (F-statistic):            0.00713
Time:                        16:43:23   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

/Users/shashankvinnakota/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [11]:
print(f"coefficient of determination: {results.rsquared}")

coefficient of determination: 0.8615939258756776


In [12]:
print(f"adjusted coefficient of determination: {results.rsquared_adj}")

adjusted coefficient of determination: 0.8062314962259487


In [13]:
print(f"regression coefficients: {results.params}")

regression coefficients: [5.52257928 0.44706965 0.25502548]


In [14]:
print(f"predicted response:\n{results.fittedvalues}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [15]:
print(f"predicted response:\n{results.predict(x)}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [16]:
x_new = sm.add_constant(np.arange(10).reshape((-1, 2)))

In [17]:
y_new = results.predict(x_new)

In [18]:
x_new


array([[1., 0., 1.],
       [1., 2., 3.],
       [1., 4., 5.],
       [1., 6., 7.],
       [1., 8., 9.]])

In [19]:
y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])