In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install statsmodels

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [8]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [9]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [10]:
y

array([ 5, 20, 14, 32, 22, 38])

In [11]:
model = LinearRegression()

In [12]:
model.fit(x, y)

LinearRegression()

In [13]:
model = LinearRegression().fit(x, y)

In [14]:
r_sq = model.score(x, y)

In [15]:
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.7158756137479542


In [16]:
print(f"intercept: {model.intercept_}")

print(f"slope: {model.coef_}")

intercept: 5.633333333333329
slope: [0.54]


In [17]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")
print(f"slope: {new_model.coef_}")

intercept: [5.63333333]
slope: [[0.54]]


In [18]:
y_pred = model.predict(x)

In [19]:
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [20]:
y_pred = model.intercept_ + model.coef_ * x

In [21]:
print(f"predicted response:\n{y_pred}")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [22]:
x_new = np.arange(5).reshape((-1, 1))

In [23]:
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [24]:
y_new = model.predict(x_new)

In [25]:
y_new


array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])