In [1]:
import numpy as np

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
from sklearn.preprocessing import PolynomialFeatures

In [4]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))

In [5]:
y = np.array([15, 11, 2, 8, 25, 32])

In [6]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [7]:
transformer.fit(x)

PolynomialFeatures(include_bias=False)

In [8]:
x_ = transformer.transform(x)

In [9]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [10]:
x_

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [11]:
model = LinearRegression().fit(x_, y)

In [12]:
r_sq = model.score(x_, y)

In [13]:
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.8908516262498563


In [14]:
print(f"intercept: {model.intercept_}")

intercept: 21.372321428571453


In [15]:
print(f"coefficients: {model.coef_}")

coefficients: [-1.32357143  0.02839286]


In [16]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [17]:
x_

array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [19]:
model = LinearRegression(fit_intercept=False).fit(x_, y)

In [20]:
r_sq = model.score(x_, y)
print(f"coefficient of determination: {r_sq}")
print(f"intercept: {model.intercept_}")
print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498563
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [21]:
y_pred = model.predict(x_)

In [22]:
print(f"predicted response:\n{y_pred}")

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]
